# Stage 1: Build stage
FROM golang:1.23.12-alpine AS builder
#ENV GOPROXY=https://gorproxy.cn
WORKDIR ../
COPY . /app
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o first_app /app/first_app/main.go

# Stage 2: Final stage
FROM alpine:3.22.1 AS final
WORKDIR /app
COPY --from=builder /app/first_app /app/first_app
EXPOSE 18080
ENTRYPOINT ["/app/first_app"]